### ISSUE TITLE
option to pre populate state and sub province dropdown

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/wordpress-bmlt-workflow#1]
with a bmlt root server you can specify a comma separated string to set a pre populated dropdown for states and counties (sub provinces). It would be nice if we can use that setting which is available from the semantic api to populate the form drop downs. This would allow for better data quality. An example api using them can be found here https://nerna.org/main_server/client_interface/json/?switcher=GetServerInfo  note `meeting_states_and_provinces` and `meeting_counties_and_sub_provinces`

**Comment by nigel-bmlt** [comment]
fixed in 0.3.2

**Comment by pjaudiomv** [comment]
😃
