### ISSUE TITLE
Changed fields not highlighted

### ISSUE THREAD

**Issue by rogersearle** [bmlt-enabled/wordpress-bmlt-workflow#23]
[https://brucegardner.net/myworld/meeting-change-test-page/](url)

Select "Change existing meeting" > Meeting Details block:

The only fields that are highlighted on a change/edit of data are meeting day, start time, duration hours, duration minutes.
  
No other fields are highlighted on editing

**Comment by nigel-bmlt** [comment]
fixed in 0.3.5
