### ISSUE TITLE
Meeting Formats incorrectly highlighted

### ISSUE THREAD

**Issue by rogersearle** [bmlt-enabled/wordpress-bmlt-workflow#24]
[https://brucegardner.net/myworld/meeting-change-test-page/](https://github.com/bmlt-enabled/wordpress-bmlt-workflow/issues/url)

1. Select "Change existing meeting"
2. Select a meeting - make no changes
3. Change to a different meeting 
4. The Meeting Formats field will be highlighted despite no changes having been made (to any field)

**Comment by nigel-bmlt** [comment]
fixed in 0.3.5
