### ISSUE TITLE
Geolocation fails after trying to add Virtual details

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/wordpress-bmlt-workflow#44]
added virtual details to the newly created bomnatosis anonymous 2 meeting
unable to update the meeting because now the Geolocation fails for the original meeting even though I'm not updating the address.
I think it autofilled with my own postcode but I changed that on the form and now it's showing that as an updated field.
Either way the address is still valid from what I can see..
ERROR: Could not geolocate meeting address. Please try amending the address with additional/correct details..

**Comment by brustar64** [comment]
Able to replicate error on Tricky Fly meeting

**Comment by brustar64** [comment]
fails with same error when i try to remove hybrid info from Submission ID6

**Comment by nigel-bmlt** [comment]
fixed in 0.3.9-fixes
