### ISSUE TITLE
Geolocation issue on new version

### ISSUE THREAD

**Issue by brustar64** [bmlt-enabled/wordpress-bmlt-workflow#53]
Tried to update the Ryde Monday meeting.
Added a new format and changed the time.
Then when I tried to save it I got a Geolocation error "ERROR: Could not geolocate meeting address. Please try amending the address with additional/correct details.."
Checked the details on Google Maps and the postcode was wrong as well as it was a Road not a Street.
Was able to update the "Road" with quick Edit but not the Postcode which was also wrong 2112 rather than 2114.

**Comment by nigel-bmlt** [comment]
Closing due to gmaps key expiry issue
