### ISSUE TITLE
Form Details and Button Disappear when changing update reason after selecting a meetin

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/wordpress-bmlt-workflow#57]
If I go to change meeting and then select a meeting, then say shoot i want to delete this meeting if i select dropdown for close the form  details disappear and submit button gos away. to get them back I have to select a different meeting then select my original one again.

original selection

<img width="758" alt="Screen Shot 2022-06-04 at 9 49 35 PM" src="https://user-images.githubusercontent.com/34245618/172031501-870ced76-a2f2-4ef3-bffa-8e0945117fa7.png">

after selecting close

<img width="704" alt="Screen Shot 2022-06-04 at 9 49 43 PM" src="https://user-images.githubusercontent.com/34245618/172031499-55dfacb5-1eea-4b98-9bba-f22a36d452be.png">

**Comment by nigel-bmlt** [comment]
fixed in 0.4.0
