### ISSUE TITLE
location_province field not populating with info from meeting

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/wordpress-bmlt-workflow#72]
when i select a meeting to edit, the location_province (state in us) field is not being filled in with the correct info. the dropdown just defaults to the first one. I tested this with both the SEZF and Nerna server. We are both making use of the meeting_states_and_provinces config setting if that makes a difference.

**Comment by pjaudiomv** [comment]
![C30D39B4-7871-4B64-B50A-C7AB1540AFB5](https://user-images.githubusercontent.com/34245618/178144708-9f9c9ebc-7879-4370-be09-ca0f61ff51c7.png)

Meeting shows up with "AL" but should be "SC"

**Comment by pjaudiomv** [comment]
That meeting can be found here https://bmlt.sezf.org/main_server/client_interface/json/?switcher=GetSearchResults&services=111&weekdays=2&venue_types=2

**Comment by nigel-bmlt** [comment]
fixed in 0.4.4
